### ISSUE TITLE
Helyx-OS cannot be started

### ISSUE THREAD

**Issue by vfinonch** [ENGYS/HELYX-OS#49]
Hello, community,

I try to install the Helix-OS on my Windows Subsystem Linux. The installation was not so simple, how it is in the description, because I have needed to install also b2zip.
Anyway, now the OS is installed, but I cannot start it from Linux.
Hier is the error code after I type ~/Engys/HELYX-OS/v2.4.0$ ./HELYX-OS.sh in the command line:
/home/vfinonch/Engys/HELYX-OS/v2.4.0/bin/launcher.conf: line 45: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)
APP=  HELYX-OS
COMMAND =  java -Xms256m -Xmx1024m -XX:+UseSerialGC -Djava.rmi.server.hostname=127.0.0.1 -jar /home/vfinonch/Engys/HELYX-OS/v2.4.0/lib/HELYX-OS.jar
Exception in thread "main" java.lang.UnsatisfiedLinkError: /home/vfinonch/Engys/HELYX-OS/jre/lib/amd64/xawt/libmawt.so: libXrender.so.1: cannot open shared object file: No such file or directory
        at java.lang.ClassLoader$NativeLibrary.load(Native Method)
        at java.lang.ClassLoader.loadLibrary1(ClassLoader.java:1939)
        at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1864)
        at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1825)
        at java.lang.Runtime.load0(Runtime.java:792)
        at java.lang.System.load(System.java:1059)
        at java.lang.ClassLoader$NativeLibrary.load(Native Method)
        at java.lang.ClassLoader.loadLibrary1(ClassLoader.java:1939)
        at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1864)
        at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1846)
        at java.lang.Runtime.loadLibrary0(Runtime.java:845)
        at java.lang.System.loadLibrary(System.java:1084)
        at sun.security.action.LoadLibraryAction.run(LoadLibraryAction.java:67)
        at sun.security.action.LoadLibraryAction.run(LoadLibraryAction.java:47)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.awt.Toolkit.loadLibraries(Toolkit.java:1648)
        at java.awt.Toolkit.<clinit>(Toolkit.java:1670)
        at java.awt.Component.<clinit>(Component.java:595)
        at sun.misc.Unsafe.ensureClassInitialized(Native Method)
        at sun.reflect.UnsafeFieldAccessorFactory.newFieldAccessor(UnsafeFieldAccessorFactory.java:43)
        at sun.reflect.ReflectionFactory.newFieldAccessor(ReflectionFactory.java:140)
        at java.lang.reflect.Field.acquireFieldAccessor(Field.java:949)
        at java.lang.reflect.Field.getFieldAccessor(Field.java:930)
        at java.lang.reflect.Field.set(Field.java:680)
        at eu.engys.launcher.StartUpMonitor.pwnSplashScreen(StartUpMonitor.java:87)
        at eu.engys.launcher.StartUpMonitor.info(StartUpMonitor.java:58)
        at eu.engys.launcher.Launcher.main(Launcher.java:50)

Could you please explain, what I need to do more to launch the OS.

Thanks in advance!

Vitaliy

**Comment by vfinonch** [comment]
Update:
the part of this problem I have solved (sudo apt-get install language-pack-en, also -de).
Now is only from:

COMMAND =  java -Xms256m -Xmx1024m -XX:+UseSerialGC -Djava.rmi.server.hostname=127.0.0.1 -jar /home/vfinonch/Engys/HELYX-OS/v2.4.0/lib/HELYX-OS.jar
Exception in thread "main" java.lang.UnsatisfiedLinkError: /home/vfinonch/Engys/HELYX-OS/jre/lib/amd64/xawt/libmawt.so: libXrender.so.1: cannot open shared object file: No such file or directory
        at java.lang.ClassLoader$NativeLibrary.load(Native Method)
        at java.lang.ClassLoader.loadLibrary1(ClassLoader.java:1939)
        at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1864)
        at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1825)
        at java.lang.Runtime.load0(Runtime.java:792)
        at java.lang.System.load(System.java:1059)
        at java.lang.ClassLoader$NativeLibrary.load(Native Method)
        at java.lang.ClassLoader.loadLibrary1(ClassLoader.java:1939)
        at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1864)
        at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1846)
        at java.lang.Runtime.loadLibrary0(Runtime.java:845)
        at java.lang.System.loadLibrary(System.java:1084)
        at sun.security.action.LoadLibraryAction.run(LoadLibraryAction.java:67)
        at sun.security.action.LoadLibraryAction.run(LoadLibraryAction.java:47)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.awt.Toolkit.loadLibraries(Toolkit.java:1648)
        at java.awt.Toolkit.<clinit>(Toolkit.java:1670)
        at java.awt.Component.<clinit>(Component.java:595)
        at sun.misc.Unsafe.ensureClassInitialized(Native Method)
        at sun.reflect.UnsafeFieldAccessorFactory.newFieldAccessor(UnsafeFieldAccessorFactory.java:43)
        at sun.reflect.ReflectionFactory.newFieldAccessor(ReflectionFactory.java:140)
        at java.lang.reflect.Field.acquireFieldAccessor(Field.java:949)
        at java.lang.reflect.Field.getFieldAccessor(Field.java:930)
        at java.lang.reflect.Field.set(Field.java:680)
        at eu.engys.launcher.StartUpMonitor.pwnSplashScreen(StartUpMonitor.java:87)
        at eu.engys.launcher.StartUpMonitor.info(StartUpMonitor.java:58)
        at eu.engys.launcher.Launcher.main(Launcher.java:50)

**Comment by vfinonch** [comment]
And one more update:

the missing bibliotheks (e.g. libXrender were installed). I hope, I am now at the last step before the successful start.
